name: Lint
on: pull_request
jobs:
    lint:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4

            - run: pip install pylint mypy .
            - run: pylint IA
            - run: mypy IA
